# Generated by Django 5.0.2 on 2024-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0004_tour_price_alter_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('content', models.TextField(max_length=500)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='tour.tour')),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
            },
        ),
    ]
