# Generated by Django 5.0.2 on 2024-02-17 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_reserve_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserved_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 17, 9, 14, 16, 711169, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
