# Generated by Django 5.0.2 on 2024-02-17 16:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_reserve_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='number_people',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of people'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=9, region='KG', unique=True),
        ),
    ]
