# Generated by Django 5.0.2 on 2024-02-17 16:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_reserve_number_people_alter_reserve_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='KG', unique=True),
        ),
    ]
