# Generated by Django 5.0.2 on 2024-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_alter_reserve_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
