# Generated by Django 5.0.2 on 2024-02-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
