# Generated by Django 5.0.2 on 2024-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
