# Generated by Django 5.0.2 on 2024-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='text',
        ),
    ]
